flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/AccelerateHS/accelerate.git
    commit: b6c1621ce2993b76b858ee2af4aa46b81fe95202
  extra-dep: true
- location:
    git: https://github.com/AccelerateHS/accelerate-cuda.git
    commit: cd8d31c24717ab1041057d1979113689ac79fead
  extra-dep: true
extra-deps:
- accelerate-1.0.0.0
- cuda-0.7.5.2
- unique-0
resolver: lts-6.30
