flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/AccelerateHS/accelerate.git
    commit: 6ad36a2416d584060ba0e6b5f3d63d7af6948edd
  extra-dep: true
- location:
    git: https://github.com/AccelerateHS/accelerate-cuda.git
    commit: d5c94d0a3876f10f69fa6297cb0f380215a31ed9
  extra-dep: true
extra-deps:
- accelerate-2.0.0.0
- cuda-0.7.5.2
- unique-0
resolver: lts-6.30
